load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")



http_archive(
    name = "com_github_facebook_rocksdb",
    url = "https://github.com/facebook/rocksdb/archive/v6.26.0.tar.gz",
    strip_prefix = "rocksdb-6.26.0",
    sha256 = "b793066463da71d31a46f31946e4fca435a7c3e73435e2bb1d062d95e0a20116",
    build_file = "//:third-party/com_github_facebook_rocksdb/BUILD",
)

bind(
    name = "rocksdb",
    actual = "@com_github_facebook_rocksdb//:rocksdb",
)

http_archive(
    name = "com_github_facebook_zstd",
    urls = ["https://github.com/facebook/zstd/archive/v1.4.4.tar.gz",],
    strip_prefix = "zstd-1.4.4",
    build_file = "//:third-party/zstd.BUILD",
    sha256 = "a364f5162c7d1a455cc915e8e3cf5f4bd8b75d09bc0f53965b0c9ca1383c52c8",
)

bind(
    name = "zstd",
    actual = "@com_github_facebook_zstd//:zstd",
)

http_archive(
    name = "com_github_lz4_lz4",
    urls = ["https://github.com/lz4/lz4/archive/v1.9.2.tar.gz"],
    strip_prefix = "lz4-1.9.2",
    build_file = "//:third-party/lz4.BUILD",
    sha256 = "658ba6191fa44c92280d4aa2c271b0f4fbc0e34d249578dd05e50e76d0e5efcc",
)
bind(
    name = "lz4",
    actual = "@com_github_lz4_lz4//:lz4",
)
http_archive(
    name = "com_github_google_snappy",
    url = "https://github.com/google/snappy/archive/ed3b7b2.tar.gz",
    strip_prefix = "snappy-ed3b7b242bd24de2ca6750c73f64bee5b7505944",
    sha256 = "88a644b224f54edcd57d01074c2d6fd6858888e915c21344b8622c133c35a337",
    build_file = "//:third-party/snappy.BUILD",
)

bind(
    name = "snappy",
    actual = "@com_github_google_snappy//:snappy",
)

bind(
    name = "snappy_config",
    actual = "//third-party/snappy_config:config"
)

git_repository(
    name = "com_github_madler_zlib",
    remote = "https://github.com/madler/zlib.git",
    tag = "v1.2.11",
    #sha256 = "629380c90a77b964d896ed37163f5c3a34f6e6d897311f1df2a7016355c45eff",
    build_file = "//:third-party/zlib.BUILD",
)

bind(
    name = "zlib",
    actual = "@com_github_madler_zlib//:zlib",
)

http_archive(
  name = "com_google_googletest",
  strip_prefix = "googletest-0fe96607d85cf3a25ac40da369db62bbee2939a5",
  url = "https://github.com/google/googletest/archive/0fe96607d85cf3a25ac40da369db62bbee2939a5.tar.gz",
)

bind(
    name = "gtest",
    actual = "@com_google_googletest//:gtest",
)
http_archive(
  name = "com_github_google_glog",
  build_file = "//:third-party/glog.BUILD",
  strip_prefix = "glog-a6a166db069520dbbd653c97c2e5b12e08a8bb26",
  url = "https://github.com/google/glog/archive/a6a166db069520dbbd653c97c2e5b12e08a8bb26.tar.gz"
)

bind(
    name = "glog",
    actual = "@com_github_google_glog//:glog",
)

http_archive(
  name = "com_github_gflags_gflags",
  strip_prefix = "gflags-46f73f88b18aee341538c0dfc22b1710a6abedef",
  url = "https://github.com/gflags/gflags/archive/46f73f88b18aee341538c0dfc22b1710a6abedef.tar.gz",
)

bind(
    name = "gflags",
    actual = "@com_github_gflags_gflags//:gflags",
)

http_archive(
    name = "com_github_facebookresearch_faiss",
    build_file = "//:third-party/com_github_facebookresearch_faiss/BUILD",
    strip_prefix = "faiss-1.7.4",
    url = "https://github.com/facebookresearch/faiss/archive/refs/tags/v1.7.4.tar.gz",
)

bind(
    name = "faiss",
    actual = "@com_github_facebookresearch_faiss//:faiss",
)

http_archive(
    name = "com_github_xianyi_OpenBLAS",
    build_file = "//:third-party/com_github_xianyi_OpenBLAS/BUILD",
    strip_prefix = "OpenBLAS-0.3.24",
    url = "https://github.com/xianyi/OpenBLAS/archive/refs/tags/v0.3.24.tar.gz",
)

bind(
    name = "openblas",
    actual = "@com_github_xianyi_OpenBLAS//:openblas",
)